// <auto-generated />
namespace RestaurantApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrderIDDeleteRename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderIDDeleteRename));
        
        string IMigrationMetadata.Id
        {
            get { return "202106102138157_OrderIDDeleteRename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
